sudo: enabled

language: go
go:
  - "1.9.2"

services:
  - docker

jobs:
  include:
  - stage: tests
    install:
    - sudo pip install cpplint
    - make init
    - docker pull gcc:8.1.0
    - docker tag gcc:8.1.0 docker.mobike.io/databases/gcc:8.1.0
    - docker pull golang:1.9.2
    - docker tag golang:1.9.2 docker.mobike.io/databases/golang:1.9.2
    - docker pull quay.io/coreos/etcd:v3.3.2
    - docker tag quay.io/coreos/etcd:v3.3.2 docker.mobike.io/databases/etcd:v3.3.2
    script:
    - make lint
    - make docker-agent
    - docker run --rm --name make_test -v `pwd`:/go/src/git.mobike.io/database/mysql-agent -w /go/src/git.mobike.io/database/mysql-agent docker.mobike.io/databases/golang:1.9.2 make test
    - docker build etc/mysql-image/5.7.22-pmm/ -t docker.mobike.io/databases/mysql:5.7.22-pmm
    - make integration-test
    after_failure:
    - make clean-data

  - stage: publish
    if: tag IS present
    env: DOCKER_IMAGE=$DOCKER_USERNAME/mysql-agent:$TRAVIS_TAG
    install:
    - docker pull gcc:8.1.0
    - docker tag gcc:8.1.0 docker.mobike.io/databases/gcc:8.1.0
    - docker pull golang:1.9.2
    - docker tag golang:1.9.2 docker.mobike.io/databases/golang:1.9.2
    - make docker-agent
    - docker build etc/mysql-image/5.7.22-pmm/ -t docker.mobike.io/databases/mysql:5.7.22-pmm
    script:
    - echo "$TRAVIS_BRANCH v.s $TRAVIS_TAG"
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/mysql-agent:$TRAVIS_TAG ./etc/docker-compose/agent
    - docker push $DOCKER_USERNAME/mysql-agent:$TRAVIS_TAG
    - docker image rm $DOCKER_USERNAME/mysql-agent:$TRAVIS_TAG
    - docker image prune -f

