- job_name: mysql-agent
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: localhost:8500
    datacenter: dc1
    tag_separator: ','
    scheme: http
    services:
    - mysql-agent:metrics
  basic_auth:
    username: pmm
    password: pmm
  tls_config:
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_consul_service_id]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
